<?php

/**
 * @file
 * Work with modal form.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_entity_view_mode_alter().
 */
function fleur_add_to_cart_modal_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  // For product, change the view mode when it is full and modal mode.
  if ($entity->getEntityTypeId() == 'commerce_product' && $view_mode == 'full') {
    if (\Drupal::request()->query->get('_wrapper_format') == 'drupal_modal') {
      $view_mode = 'modal';
    }
  }
}

/**
 * Implements hook_form_alter().
 */
function fleur_add_to_cart_modal_form_commerce_order_item_add_to_cart_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Change submit redirect.
  if (isset($form['actions']['submit']['#submit'])) {
    $submit = &$form['actions']['submit']['#submit'];
    $index = array_search("::submitForm", $submit);
    if ($index !== false) {
      $submit[$index] = 'fleur_add_to_cart_modal_redirect_submit';
    }
  }

  // Change color field label.
  if (isset($form['field_color']['widget'][0]['color'])) {
    $form['field_color']['widget'][0]['color']['#title'] = t('Select color:');
  }

  // Change size options names.
  if (isset($form['purchased_entity']['widget'][0]['attributes']['attribute_size']['#options'])) {
    $size_options = &$form['purchased_entity']['widget'][0]['attributes']['attribute_size']['#options'];

    /** @var \Drupal\commerce_price\CurrencyFormatter $currency_formatter */
    $currency_formatter = \Drupal::service('commerce_price.currency_formatter');

    /** @var \Drupal\commerce_price\Price[] $price */
    $prices = [];

    /** @var \Drupal\commerce_product\Entity\ProductVariationInterface[] $variations */
    $variations = $form_state->getStorage()['product']->getVariations();
    foreach ($variations as $variation) {
      $prices[$variation->getAttributeValue('attribute_size')->id()] = $variation->getPrice();
    }

    foreach ($size_options as $id => $label) {
      $size_options[$id] = t('@label (@price)', [
        '@label' => $label,
        '@price' => $currency_formatter->format($prices[$id]->getNumber(), $prices[$id]->getCurrencyCode())
      ]);
    }
  }
}

/**
 * Change standard AddToCard submit.
 *
 * @param array $form
 *   The form elements.
 * @param FormStateInterface $form_state
 *   The form interface.
 */
function fleur_add_to_cart_modal_redirect_submit(array &$form, FormStateInterface $form_state) {
  // Get form object.
  $form_object = $form_state->getFormObject();
  // Call default submit.
  $form_object->submitForm($form, $form_state);

  $form_state->setRedirect('fleur_add_extras.form');
}
