<?php

use Drupal\Core\Form\FormStateInterface;
/**
 * Implements hook_field_widget_form_alter().
 */
function fleur_address_field_widget_form_alter(&$element, FormStateInterface &$form_state, $context) {
//    if (get_class($context['widget']) === 'Drupal\Core\Field\Plugin\Field\FieldWidget\OptionsButtonsWidget' && $context['items']->getName()==='field_address_type') {
//        $element['#attached'] = [
//            'library' => ['fleur_address/address_type'],
//        ];
//    }
}
