<?php

/**
 * @file
 * Work with modal form.
 */

use Drupal\Core\Entity\EntityInterface;

/**
 * Implements hook_entity_view_mode_alter().
 */
function fleur_modal_view_entity_view_mode_alter(&$view_mode, EntityInterface $entity, $context) {
  // For product, change the view mode when it is full and modal mode.
  if ($entity->getEntityTypeId() == 'commerce_product' && $view_mode == 'full') {
    if (\Drupal::request()->query->get('_wrapper_format') == 'drupal_modal') {
      $view_mode = 'modal';
    }
  }
}