<?php

/**
 * @file
 * Provides entity operations functionality.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;

/**
 * Implements hook_entity_operation().
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *
 * @return array
 */
function fleur_order_operations_entity_operation(EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'commerce_order') {
    $operations = [];
    $operations['order_again'] = [
      'title' => t('Order again'),
      'url' => Url::fromRoute('entity.order_again.collection', [
        'commerce_order' => $entity->id()
      ]),
      'weight' => 50,
    ];
    return $operations;
  }
}
